"""add file_hash column

Revision ID: 702f65287b5f
Revises: e96521d462d6
Create Date: 2026-03-05 00:02:29.183283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702f65287b5f'
down_revision: Union[str, Sequence[str], None] = 'e96521d462d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_analyses_file_hash'), 'analyses', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_file_hash'), table_name='analyses')
    op.drop_column('analyses', 'file_hash')
    # ### end Alembic commands ###
